name: Tests No Docker
'on': [push,workflow_dispatch]
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Dump environment
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: '${{ toJson(github) }}'
        run: echo "$GITHUB_CONTEXT"
      - name: Setup Docker container
        shell: bash
        run: |2-
                    export DEBIAN_FRONTEND=noninteractive
                    apt-get update
                    apt-get -y install \
                      git \
                      git-lfs \
                      curl \
                      clang \
                      sudo \
                      docker.io

                    curl https://sh.rustup.rs -sSf | sh -s -- -y
                    source $HOME/.cargo/env
                    echo "$HOME/.cargo/bin:/usr/lib/go-1.17/bin/:$PATH" >> "$GITHUB_PATH"
                    echo "CROSS_DOCKER_IN_DOCKER=true" >> "$GITHUB_ENV"
                    rustup update
                    rustup toolchain install stable --target x86_64-unknown-linux-gnu --profile minimal --component cargo rust-src rustfmt
                    cargo install cross
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        shell: bash
        run: |2-
            cross build -vv --target x86_64-unknown-linux-gnu 
